### ISSUE TITLE
UI interface, spesifially the main page is very small on high resolutions.

### ISSUE THREAD

**Issue by sandpatch** [gdzx/chernobyl-simulator#2]
I use the 2560 × 1440 resolution, and I can't see any umber displayed on the main page. They are just replaced by boxes.
![Capture](https://user-images.githubusercontent.com/23266782/202677987-d2c3cb11-461b-4a21-9a0d-9d13e8f329c6.JPG)

**Comment by gdzx** [comment]
For the scaling issue, I'm afraid responsive design wasn't a thing in Visual Basic 3.0 and the recommended resolution for this game was 1024x768, so this isn't something I can easily fix.

For the control room page, displaying the actual numbers is a feature of the remastered version that wasn't present in the original game, so the "boxes" you see are actually showing `000.0` (the background is just a static image).

The good news is that given your screen real estate, you should be able to open pretty much all the control panels at the same time, which is way better IMO than the tiny control room overview.

**Comment by sandpatch** [comment]
Yeah, I do have space so it's not really a problem.
