### ISSUE TITLE
Overflow crashes

### ISSUE THREAD

**Issue by Amselfass** [gdzx/chernobyl-simulator#4]
Hi gdzx!

I'm not sure how active this project is, but I'll open this issue nonetheless in the hope that maybe it will be seen. :-)

I'm running the simulator on Windows 11 with winevdm 0.9.0 and I frequently receive "Overflow" error messages when operating pumps or valves. Unfortunately, I cannot give detailed reproduction steps, as the crashes are not guaranteed to happen even when following the exact same sequence of button presses from the same IC file. So far, I have observed the problem when operating the condenser circulator pumps, when operating the feed pumps, and when toggling the reactor level control between manual and automatic.

The problem manifests itself as a message box simply stating "Overflow". When clicking "OK" or closing the message box, the simulator closes.

I'm happy to provide whatever additional information is needed to help track down the problem.

**Comment by gdzx** [comment]
Hi!

Can you try installing [this version](https://github.com/gdzx/chernobyl-simulator/releases/download/v0.1.0/chernobyl-setup.exe) from the releases pages?

otvdm is not exactly up-to-date in it, but this is the only one I have tested. Maybe something changed with the latest version.

**Comment by Amselfass** [comment]
Sorry, I think I was too unclear in my wording. The version of chernobyl-setup.exe that you linked in your response is the one I installed. It wouldn't run on my PC (Windows gave an "This program can't run on your PC" error), so I found #3, went to https://github.com/otya128/winevdm and installed their latest release 0.9.0.

**Comment by gdzx** [comment]
Can you try running it with the version installed in `C:\Chrnobyl\otvdm`?

**Comment by Amselfass** [comment]
Ah, I did not realize you had packed a version of otvdm with your release. My bad! I'll try it out right now.

**Comment by gdzx** [comment]
Note that the installer is supposed to create the appropriate start menu shortcuts under the folder "Chernobyl Simulator" to launch the various executables through the builtin otvdm version, but I guess you also have shortcuts pointing directly to the 16-bit executables...

**Comment by Amselfass** [comment]
I apologize, I don't often use the start menu, so I just launched `icselect.exe` straight from Windows Explorer. I now realize that that's not the correct procedure and I'm instead supposed to open it with your supplied `otvdmw.exe`.

I just went through the full start-up sequence in the "Plant Manager" scenario without any errors, so you can consider this issue resolved. Many thanks for your help! It's really appreciated, especially on such short notice for such an obscure piece of software. :-)

It's getting a bit late for me now, but if you want, I can try to get a screenshot of the error window tomorrow.

**Comment by gdzx** [comment]
> I apologize, I don't often use the start menu, so I just launched icselect.exe straight from Windows Explorer. I now realize that that's not the correct procedure and I'm instead supposed to open it with your supplied otvdmw.exe.

I will add these instructions to the README.

> I just went through the full start-up sequence in the "Plant Manager" scenario without any errors, so you can consider this issue resolved. Many thanks for your help! It's really appreciated, especially on such short notice for such an obscure piece of software. :-)

You're welcome!

> It's getting a bit late for me now, but if you want, I can try to get a screenshot of the error window tomorrow.

Thanks, but further investigation isn't necessary, I should be able to replicate it. If you encounter any further issues, feel free to reach out.

Enjoy the game!
