### ISSUE TITLE
unit system used ?

### ISSUE THREAD

**Issue by LetMePickThat** [gdzx/chernobyl-simulator#7]
Hi @gdzx, thank you for that port !

Quick question: is the game set up to use imperial or metric units ? The original game allowed the user to toogle between both through  the OPTIONS menu, but said menu doesnt appear to be available in your version of the game. Perhalps I have missed something...

Thanks.

**Comment by gdzx** [comment]
Hi,

This menu is in an auxiliary window:

![unit-option](https://github.com/gdzx/chernobyl-simulator/assets/6490707/80205fb5-663f-456b-b948-cb95da837871)

Best regards,

**Comment by LetMePickThat** [comment]
My bad. Works as expected.

Closing the issue, and thanks for the quick answer.
